# Generated by Django 3.2.3 on 2021-05-27 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('leagueCode', models.CharField(choices=[('PL', 'Premier League'), ('PD', 'La Liga'), ('SA', 'Serie A'), ('BL1', 'Bundesliga'), ('FL1', 'Ligue 1')], max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='league code')),
                ('name', models.CharField(max_length=56)),
                ('logo', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.CharField(max_length=32, unique=True)),
                ('homeTeamScore', models.IntegerField(null=True)),
                ('awayTeamScore', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('result', models.CharField(max_length=56, null=True)),
                ('status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='MyLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True)),
                ('myLeagueId', models.CharField(max_length=8, unique=True)),
                ('leagues', models.ManyToManyField(to='api.League', verbose_name='league')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='players')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=56)),
                ('logo', models.URLField()),
                ('form', models.CharField(max_length=12)),
                ('position', models.IntegerField()),
                ('playedGames', models.IntegerField()),
                ('won', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goalsScored', models.IntegerField()),
                ('goalsAgainst', models.IntegerField()),
                ('goalDifference', models.IntegerField()),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.league')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=56)),
                ('points', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('myLeague', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.myleague')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('leagueCode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.league', verbose_name='league')),
            ],
            options={
                'unique_together': {('leagueCode', 'number')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='awayTeam', to='api.team', verbose_name='away team'),
        ),
        migrations.AddField(
            model_name='match',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='homeTeam', to='api.team', verbose_name='home team'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.league', verbose_name='league'),
        ),
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.matchday'),
        ),
    ]
