repos:
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    exclude: ^.*\b(migrations)\b.*$
    language_version: python3
    args: [--line-length=79]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8
    exclude: ^.*\b(migrations)\b.*$
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.8.0  
  hooks:
    - id: python-use-type-annotations      

